### ISSUE TITLE
Poor video streaming performance: reduce minimum bandwidth

### ISSUE THREAD

**Issue by dgudiel** [bluerobotics/ardusub-gitbook#140]
In the section for [Poor Video Streaming Performance troubleshooting](https://www.ardusub.com/troubleshooting/troubleshooting.html#poor-video-streaming-performance), "Systems with bandwidths below 40Mbps should be diagnosed for issues.", 40Mbps should be reduced to 15Mbps.

**Comment by jaxxzer** [comment]
Done
