### ISSUE TITLE
Troubleshooting Page missing section for Resetting MavProxy Options

### ISSUE THREAD

**Issue by dgudiel** [bluerobotics/ardusub-gitbook#160]
Current troubleshooting page linked in left sidebar is missing [Reset MavProxy Options section](https://www.ardusub.com/troubleshooting/troubleshooting.html#reset-mavproxy-options).

**Comment by jaxxzer** [comment]
There are two copies of the `troubleshooting.md` in the repository, the information needs to be consolidated into the one under `./reference/`
