### ISSUE TITLE
pymavlink: add depth hold example (set target depth)

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/ardusub-gitbook#195]
[ArduSub supports](https://github.com/ArduPilot/ardupilot/blob/Sub-4.0/ArduSub/GCS_Mavlink.cpp#L657-L717) setting the target depth in depth hold mode using the [`SET_POSITION_TARGET_GLOBAL_INT`](
https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_GLOBAL_INT) message. I couldn't find a more recent usage example than @Williangalvani's [gist](https://gist.github.com/Williangalvani/78859b23d6eebdd899a1c2a5ece20804) from a while ago, so I'm not sure if that code will actually work in ArduSub >=4.0 (it was written for a specific version of ArduSub 3.6), but it would be good if we could clean that up and add an example to our docs.

**Comment by Williangalvani** [comment]
just tested the gist on 4.0.3 and it works fine. Would you mind cleaning it up to add in the docs?
