### ISSUE TITLE
Doc Bug: Pymavlink · ArduSub GitBook

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub-gitbook#48]
Conflict between docs and result:

https://discuss.bluerobotics.com/t/converting-bluerov2-to-auv/3859/3

Bug Page: [Pymavlink · ArduSub GitBook](https://www.ardusub.com/developers/pymavlink.html#pymavlink)

**Comment by patrickelectric** [comment]
@jaxxzer, just tested and everything is working this this version under linux and mac. The guy is using freeze and that can explain why he's not get the output.

**Comment by patrickelectric** [comment]
@Williangalvani 	can you confirm this ?

**Comment by patrickelectric** [comment]
Ok, I did a fresh install on windows in this same version, everything is working fine.

**Comment by jaxxzer** [comment]
>  in this version

> in this same version

Which versions? Should we be more explicit in the doc or it's ok?

**Comment by patrickelectric** [comment]
I'm going to send a PR to make it more explicit to use python interactive shell.
