### ISSUE TITLE
Doc Bug: Pymavlink · ArduSub GitBook

### ISSUE THREAD

**Issue by vshie** [bluerobotics/ardusub-gitbook#50]
DESCRIBE PROBLEM WITH DOCS HERE

Bug Page: [Pymavlink · ArduSub GitBook](https://www.ardusub.com/developers/pymavlink.html)

Change flight mode example provided reads as if it will command vehicle mode to Stabilize - however when executed changes vehicle mode to Depth hold

**Comment by jaxxzer** [comment]
Everything is working fine here.

At 192.168.2.2:8088 terminal:
```
pi@raspberrypi:~ $ screen -r mavproxy
```

Run command on surface computer:
```
$ python test.py 
Command ACCEPTED and EXECUTED
```


Appears in mavproxy console:
```
MANUAL> Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}                 
STABILIZE> Mode STABILIZE
```

**Comment by jaxxzer** [comment]
Is QGC open while you are doing this? Try closing it.
