### ISSUE TITLE
pymavlink examples

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub-gitbook#7]
Examples of how to interface with the rov using pymavlink:

Managing mavproxy inputs/outputs
Stopping mavproxy
Running script locally on ROV vs running on remote client.

- [x] Serial connection
- [x] UDP connection
- [x] Camera tilt
- [x] lights control
- [x] mode change
- [x] arming/disarming
- [x] manual control
- [x] read depth
- [x] read attitude
- [x] restart

**Comment by patrickelectric** [comment]
Done o/
