### ISSUE TITLE
Add mavlogdump.py, mavlogreplay.py, and MAVExplorer.py examples

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub-gitbook#9]
To the logging page

**Comment by jaxxzer** [comment]
We can link to this http://ardupilot.org/dev/docs/using-mavexplorer-for-log-analysis.html
This article needs some help in the area of windows/mac installation and clear examples for simple data, and where to find available data fields (tab completion).

**Comment by Williangalvani** [comment]
This looks stale. We have both mavlogdump and mavexplorer right now. The link is also there, we don't have mavreplay there but I don't think that is really useful...

I'll close this, feel free to re-open if you disagree
